// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSX0YzRWvnUISYbf_DNEZ4cZNQtREnKeE',
    appId: '1:375585344643:web:29fd6875d838e4d7ea9fb6',
    messagingSenderId: '375585344643',
    projectId: 'besports-841e2',
    authDomain: 'besports-841e2.firebaseapp.com',
    storageBucket: 'besports-841e2.appspot.com',
    measurementId: 'G-MKJ71Q7451',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGnl32I4B3pv09DMCBusgLQ8ESTBQYKc',
    appId: '1:375585344643:android:1f2e022e7f1fd502ea9fb6',
    messagingSenderId: '375585344643',
    projectId: 'besports-841e2',
    storageBucket: 'besports-841e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHoZGd4fvg0RKSOeWZL6Poa900kC-w9hw',
    appId: '1:375585344643:ios:ef3adc11a7576718ea9fb6',
    messagingSenderId: '375585344643',
    projectId: 'besports-841e2',
    storageBucket: 'besports-841e2.appspot.com',
    iosClientId: '375585344643-pujpmildc1fankfe72f4l80iq0q8fv67.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApplication',
  );
}
